"""
Plan Creator Skill - Bronze Tier AI Employee

Generates execution plans for tasks based on their metadata.
"""

import os
from pathlib import Path
from datetime import datetime
from typing import Dict


class PlanCreator:
    def __init__(self, vault_path: str):
        self.vault_path = Path(vault_path)
        self.plans_folder = self.vault_path / "Plans"
        self.plans_folder.mkdir(exist_ok=True)

    def create_plan(self, task_data: Dict) -> str:
        """Create an execution plan for a task."""

        # Generate plan filename
        task_filename = task_data['filename']
        plan_filename = f"PLAN_{Path(task_filename).stem}.md"
        plan_path = self.plans_folder / plan_filename

        # Determine if approval is needed
        requires_approval = self.requires_approval(task_data)

        # Generate plan content
        plan_content = self.generate_plan_content(task_data, requires_approval)

        # Write plan to file
        with open(plan_path, 'w', encoding='utf-8') as f:
            f.write(plan_content)

        print(f"[PLAN] Created: {plan_filename}")
        return str(plan_path)

    def requires_approval(self, task_data: Dict) -> bool:
        """Determine if a task requires human approval."""

        # High priority tasks require approval
        if task_data['priority'] == 'high':
            return True

        # Email tasks require approval
        if task_data['type'] == 'email':
            return True

        # Check for sensitive keywords
        sensitive_keywords = ['invoice', 'payment', 'financial', 'delete', 'remove']
        body_lower = task_data['body'].lower()
        subject_lower = task_data['subject'].lower()

        for keyword in sensitive_keywords:
            if keyword in body_lower or keyword in subject_lower:
                return True

        return False

    def generate_plan_content(self, task_data: Dict, requires_approval: bool) -> str:
        """Generate the plan content."""

        timestamp = datetime.utcnow().isoformat() + 'Z'

        plan = f"""# Execution Plan: {task_data['subject']}

---
**Task File**: {task_data['filename']}
**Type**: {task_data['type']}
**Priority**: {task_data['priority']}
**From**: {task_data['from']}
**Created**: {timestamp}
**Requires Approval**: {'Yes' if requires_approval else 'No'}

---

## Task Summary

{task_data['body'][:200]}{'...' if len(task_data['body']) > 200 else ''}

---

## Execution Steps

"""

        if requires_approval:
            plan += """### ⚠️ Human Approval Required

This task requires human approval before execution due to:
- High priority level
- Sensitive content or actions
- Email communication involved

**Action**: Move to /Pending_Approval for review

---

## Approval Checklist

- [ ] Review task details
- [ ] Verify sender/source
- [ ] Confirm action is appropriate
- [ ] Approve or reject execution

"""
        else:
            plan += """### ✅ Automated Execution

This task can be executed automatically.

**Steps**:
1. Parse task requirements
2. Execute required actions
3. Log completion
4. Move to /Done

"""

        plan += f"""---

## Notes

- Task received: {task_data.get('received', 'N/A')}
- Status: {task_data['status']}

---

*Generated by AI Employee - Bronze Tier*
*Plan created: {timestamp}*
"""

        return plan


# Example usage
if __name__ == "__main__":
    vault_path = Path(__file__).parent.parent
    plan_creator = PlanCreator(str(vault_path))

    # Sample task data
    sample_task = {
        'filename': 'SAMPLE_TASK.md',
        'type': 'email',
        'from': 'user@example.com',
        'subject': 'Test Task',
        'priority': 'high',
        'status': 'pending',
        'body': 'This is a sample task for testing.',
        'received': '2026-04-07T23:58:00Z'
    }

    plan_path = plan_creator.create_plan(sample_task)
    print(f"\nPlan created at: {plan_path}")
